### PR TITLE
Initial implementation of json transformation

### PR DESCRIPTION
**Pull request by BorisTasevski**
Add the transfromation script form mgbench JSON format to benchgraph JSON format.

### CODE REVIEW

**Comment by MarioHerceg** [comment]
Can you give a short info on how to run this?

**Comment by BorisTasevski** [comment]
> Can you give a short info on how to run this?

In transform.py change source(path to source json) and destination (path where destination json should be saved) and run transform.py

**Comment by MarioHerceg** [comment]
> > Can you give a short info on how to run this?
> 
> In transform.py change source(path to source json) and destination (path where translated json should be saved) and run transform.py

Can this be later added as an input to `transform.py`? So the run would look something like `python3 transform.py ./results/memgraph-hot.json ./transformed-results/memgraph-hot.json`? I am asking this so I can automate this process later on.

**Comment by BorisTasevski** [comment]
> > > Can you give a short info on how to run this?
> > 
> > 
> > In transform.py change source(path to source json) and destination (path where translated json should be saved) and run transform.py
> 
> Can this be later added as an input arguments to `transform.py`? So the run would look something like `python3 transform.py ./results/memgraph-hot.json ./transformed-results/memgraph-hot.json`? I am asking this so I can automate this process later on.

Yes

**Comment by antejavor** [comment]
@MarioHerceg Let's look at this tomorrow and correct what is needed so we can merge this.

**Review by antejavor — APPROVED** [review]

**Pull request merged**
